server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: route-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/travel_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
  cloud:
    nacos:
      discovery:
        enabled: ${SPRING_CLOUD_NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR:localhost:8848}
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP:127.0.0.1}
      config:
        enabled: ${SPRING_CLOUD_NACOS_CONFIG_ENABLED:false}
    sentinel:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true

logging:
  level:
    com.example.route: DEBUG