server:
  port: 8083

spring:
  application:
    name: route-service
  datasource:
    url: jdbc:mysql://localhost:3309/travel_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        ip: 127.0.0.1
      config:
        enabled: false
    sentinel:
      enabled: false

logging:
  level:
    com.example.route: DEBUG