server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
        - id: route-service
          uri: lb://route-service
          predicates:
            - Path=/api/route/**
        - id: attraction-service
          uri: lb://attraction-service
          predicates:
            - Path=/api/attraction/**
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotel/**
        - id: favorite-service
          uri: lb://favorite-service
          predicates:
            - Path=/api/favorite/**
      default-filters:
        - StripPrefix=1
