server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        enabled: false
        register-enabled: false
      config:
        enabled: false
