server:
  port: 8082

spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        ip: 127.0.0.1
      config:
        enabled: false
    sentinel:
      transport:
        dashboard: localhost:8718
        port: 8720

logging:
  level:
    com.example.ai: DEBUG