server:
  port: 8085

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:mysql://localhost:3309/travel_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        ip: 127.0.0.1
      config:
        enabled: false
    sentinel:
      enabled: false

logging:
  level:
    com.example.hotel: DEBUG